channels:
- conda-forge
dependencies:
- python=3.7.6
- pip<=23.0.1
- pip:
  - mlflow
  - argparse==1.4.0
  - boto3==1.26.82
  - cffi==1.15.1
  - defusedxml==0.7.1
  - fsspec==2023.1.0
  - keras==2.11.0
  - pandas==1.3.5
  - pillow==9.4.0
  - pydot==1.4.2
  - scipy==1.7.3
  - tensorflow-intel==2.11.0
  - tensorflow==2.11.0
name: mlflow-env
